import {
  acs1,
  acs2,
  acs3,
  acs4,
  cup1,
  cup2,
  cup3,
  cup4,
  knife1,
  knife2,
  knife3,
  knife4,
  pan1,
  pan2,
  pan3,
  pan4,
} from "../public";

export const products = [
  {
    id: 1,
    title: "Nồi Áp Suất AMT",
    img: pan4,
    status: "Còn hàng",
    price: "6300000",
    type: "Nồi",
    brand: "atm",
    catagories: "pans",
    tag: "sale",
    saleprice: "650000",
  },
  {
    id: 2,
    title: "Khay Oval STAUB Màu Đen",
    img: pan2,
    status: "Còn hàng",
    price: "3190000",
    type: "Khay",
    brand: "staub",
    catagories: "pans",
  },
  {
    id: 3,
    title: "Lodge - Khay Gang Nướng Đa Năng - 42.55x24.13cm",
    img: pan3,
    status: "Còn hàng",
    price: "2690000",
    type: "Khay",
    brand: "lodge",
    catagories: "pans",
  },
  {
    id: 4,
    title: "Lodge - Chảo Gang Heat-Treated",
    img: pan1,
    status: "Còn hàng",
    price: "913000",
    brand: "lodge",
    type: "Chảo",
    catagories: "pans",
  },
  {
    id: 5,
    title: "Dao Nakiri FIN 2 ZWILLING - 17cm",
    img: knife1,
    status: "Còn hàng",
    price: "2390000",
    type: "Dao",
    brand: "ZWILLING",
    catagories: "knifies",
  },
  {
    id: 6,
    title: "Miyabi - Dao Rocking Santoku 5000MCD 67 - 18cm",
    img: knife2,
    status: "Còn hàng",
    price: "10900000",
    type: "Dao",
    brand: "Miyabi",
    catagories: "knifies",
    tag: "sale",
    saleprice: "11200000",
  },
  {
    id: 7,
    title: "Dao Thái Thịt Twin Master ZWILLING Màu Xanh - 18cm",
    img: knife3,
    status: "Còn hàng",
    price: "1199000",
    type: "Dao",
    brand: "ZWILLING",
    catagories: "knifies",
  },
  {
    id: 8,
    title: "Dao Nakiri FIN 2 ZWILLING - 17cm",
    img: knife4,
    status: "Còn hàng",
    price: "2390000",
    type: "Dao",
    brand: "ZWILLING",
    catagories: "knifies",
  },
  {
    id: 9,
    title: "Aderia - Arabesque - Bộ Ly Rượu Old Fashioned G&S - 0.3L - 2 Cái",
    img: cup1,
    status: "Còn hàng",
    price: "2600000",
    type: "Ly",
    brand: "Aderia",
    catagories: "cups",
  },
  {
    id: 10,
    title: "Vista Alegre - Bộ Ly Uống Coffee Gold Exotic - 2 Món",
    img: cup2,
    status: "Còn hàng",
    price: "1750000",
    type: "Ly",
    brand: "Vista Alegre",
    catagories: "cups",
  },
  {
    id: 11,
    title: "Vista Alegre - Bộ Ly Uống Coffee Caillouté - 2 Món",
    img: cup3,
    status: "Còn hàng",
    price: "3330000",
    type: "Ly",
    brand: "Vista Alegre",
    catagories: "cups",
  },
  {
    id: 12,
    title: "Vista Alegre - Bộ 2 Ly Uống Coffee Petites Histoires - 4 Món",
    img: cup4,
    status: "Còn hàng",
    price: "5076000",
    type: "Ly",
    brand: "Vista Alegre",
    catagories: "cups",
    tag: "sale",
    saleprice: "5200000",
  },
  {
    id: 13,
    title: "Zoku - Bộ Dụng Cụ Làm Kem - 8 Món",
    img: acs1,
    status: "Còn hàng",
    price: "690000",
    type: "Phụ kiện",
    brand: "Zoku",
    catagories: "accessory",
    tag: "sale",
    saleprice: "750000",
  },
  {
    id: 14,
    title: "Fresh Choice - Dụng Cụ Khui Hộp Versatile",
    img: acs2,
    status: "Còn hàng",
    price: "330000",
    type: "Phụ kiện",
    brand: "Fresh Choice",
    catagories: "accessory",
  },
  {
    id: 15,
    title: "Bộ Thau Và Rổ Nhựa Fresh Choice",
    img: acs3,
    status: "Còn hàng",
    price: "620000",
    type: "Phụ kiện",
    brand: "Fresh Choice",
    catagories: "accessory",
  },
  {
    id: 16,
    title: "Lodge - Tay Cầm Chống Nóng Citrus",
    img: acs4,
    status: "Còn hàng",
    price: "285000",
    type: "Phụ kiện",
    brand: "Lodge",
    catagories: "accessory",
  },
];

const pansSection = products.filter(
  (products) => products.catagories === "pans"
);
const knifiesSection = products.filter(
  (products) => products.catagories === "kinfies"
);
const cupsSection = products.filter(
  (products) => products.catagories === "cups"
);
const accessorySection = products.filter(
  (products) => products.catagories === "accessory"
);

export default {
  pansSection,
  knifiesSection,
  cupsSection,
  accessorySection,
};
